[tool.poetry]
name = "banking-operations"
version = "0.1.0"
description = ""
authors = ["Denys <nikeenko89@gmail.com>"]

packages = [
    { include = "banking_operations", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
pandas = "^3.0.2"
requests = "^2.33.1"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
flake8 = "^7.3.0"
mypy = "^1.20.0"
isort = "^8.0.1"
black = "^26.3.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"